apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
    env: test
  namespace: <INSERT YOUR NAMESPACE>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      env: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
        env: test
    spec:
      containers:
      - name: my-app
        image: IMAGE_TO_REPLACE
        ports:
        - containerPort: 6000
        readinessProbe:
          httpGet:
            path: /ready
            port: 6000
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /alive
            port: 6000
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
        resources:
          requests:
            memory: "100M"
            cpu: "50m"
          limits:
            memory: "100M"
            cpu: "50m"
        env:
          - name: ENV
            value: dev
