apiVersion: v1
kind: Service
metadata:
  labels:
    app: service
    env: dev
    service: my-app
  name: my-app
  namespace: <INSERT YOUR NAMESPACE>
spec:
  selector:
    app: service
    env: dev
    name: my-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http-my-app-dev
